"""change_simulation_event_severity_to_enum

Revision ID: 0431b7d7b6e5
Revises: ef5f16583147
Create Date: 2026-07-19 10:33:27.890425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0431b7d7b6e5'
down_revision: Union[str, None] = 'ef5f16583147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'simulation_events',
        'severity',
        type_=sa.Enum('Critical', 'High', 'Medium', 'Low', name='incidentseverity'),
        postgresql_using='severity::incidentseverity',
        existing_type=sa.String(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'simulation_events',
        'severity',
        type_=sa.String(),
        existing_type=sa.Enum('Critical', 'High', 'Medium', 'Low', name='incidentseverity'),
        nullable=False
    )
    # ### end Alembic commands ###
