"""create incidents table with enums

Revision ID: 741abcd02d70
Revises: e12d4a5b6789
Create Date: 2026-07-15 06:44:22.588745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741abcd02d70'
down_revision: Union[str, None] = 'e12d4a5b6789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('Critical', 'High', 'Medium', 'Low', name='incidentseverity'), nullable=False),
    sa.Column('status', sa.Enum('New', 'Investigating', 'Mitigated', 'Resolved', name='incidentstatus'), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('destination_ip', sa.String(), nullable=True),
    sa.Column('mitre_technique', sa.String(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('Authentication', 'Initial_Access', 'Execution', 'Persistence', 'Privilege_Escalation', 'Defense_Evasion', 'Credential_Access', 'Discovery', 'Lateral_Movement', 'Collection', 'Exfiltration', 'Command_and_Control', name='incidentcategory'), nullable=False),
    sa.Column('remediation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
